version: '3.1'

services:

  mqtt:
    image: eclipse-mosquitto
    ports:
      - '1883:1883'
      #- '9001:9001' for web sockets

  telegraf:
    image: telegraf
    volumes:
      - './telegraf.config:/etc/telegraf/telegraf.conf:ro'

  influxdb:
    image: influxdb
    ports:
      - '8086:8086'
      #- '2003:2003' for graphite
    volumes:
      - './influxdb-init.sh:/docker-entrypoint-initaws.d/influxdb-init.sh:ro'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
